apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idp-ingress
spec:
  ingressClassName: nginx  # this is required to tell the ingress controller which ingress class to use, since we are using nginx ingress controller, we specify nginx here
  rules:
    # - host: idp.local    #removed since we are using the default host i.e ec2 pub ip for now, but can be added back in if needed
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: idp-api-service
                port:
                  number: 80