apiVersion: v1
kind: Secret
metadata:
  name: idp-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  REDIS_HOST: "redis"
  AWS_ACCESS_KEY_ID: "replace-me"
  AWS_SECRET_ACCESS_KEY: "replace-me"